###############################################
# Do not Edit! Generated by:
# spec-builder version 0.14
###############################################

Name: moblin-panel-devices
Summary: Devices panel
Group: System Environment/Desktop
Version: 0.1.32
License: LGPL 2.1
URL: http://www.moblin.org
Release: 5.4
Source0: %{name}-%{version}.tar.gz
# PATCH-FIX-UPSTREAM moblin-panel-devices-clutter-gtk-0.90.patch dimstar@opensuse.org -- We're already at clutter-gtk-0.90.
Patch0: moblin-panel-devices-clutter-gtk-0.90.patch

BuildRequires: pkgconfig(dbus-glib-1)
BuildRequires: pkgconfig(libcanberra-gtk)
BuildRequires: pkgconfig(libpulse-mainloop-glib) >= 0.9.15
BuildRequires: pkgconfig(clutter-1.0)
BuildRequires: pkgconfig(clutter-gtk-0.10)
BuildRequires: pkgconfig(devkit-power-gobject)
BuildRequires: pkgconfig(gconf-2.0)
BuildRequires: pkgconfig(gdk-x11-2.0)
BuildRequires: pkgconfig(libnotify)
BuildRequires: mutter-moblin-devel
BuildRequires: libmx-devel

BuildRequires: intltool
BuildRequires: gettext
BuildRequires: gnome-common

Requires: mutter-moblin
Requires(post): /bin/touch

%description
Moblin devices panel

%prep
%setup -q -n %{name}-%{version}
#%patch0 -p1

%build
%configure --without-udisks --disable-static
export LD_AS_NEEDED=1
make %{?_smp_mflags}

%install
rm -rf %{buildroot}
%makeinstall

%find_lang moblin-panel-devices  || echo -n >> moblin-panel-devices.lang

mkdir -p %{buildroot}/%{_datadir}/doc/%{name}-%{version}
for f in `ls %{buildroot}/%{_datadir}/doc/`; do
	if [ -f %{buildroot}/%{_datadir}/doc/$f ]; then
		mv %{buildroot}/%{_datadir}/doc/$f %{buildroot}/%{_datadir}/doc/%{name}-%{version}
	fi
done

%clean
rm -rf %{buildroot}

%post 
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%files -f moblin-panel-devices.lang
%defattr(-,root,root,-)
%doc COPYING
%{_sysconfdir}/xdg/autostart/moblin-power-icon.desktop
%{_libexecdir}/%{name}
%dir %{_datadir}/%{name}
%dir %{_datadir}/%{name}/theme
%{_datadir}/%{name}/theme/*
%{_datadir}/%{name}/icons/*
%{_datadir}/mutter-moblin/panels/%{name}.desktop
%{_datadir}/mutter-moblin/panels/moblin-power-icon.desktop
%{_datadir}/dbus-1/services/*.service
%{_libexecdir}/moblin-power-icon


%changelog
* Wed Jul 13 2016 Wei-Lun Chao <bluebat@member.fsf.org> -
- Rebuild for Fedora
* Tue Oct 26 2010 Wei-Lun Chao <bluebat@member.fsf.org>
- Rebuild for OSSII
* Fri Aug 13 2010 awafaa@opensuse.org
- Revert to using clutter-gtk-0.10
* Mon Jul 19 2010 awafaa@opensuse.org
- Update to version 0.1.32
* Mon Jun 14 2010 dimstar@opensuse.org
- We are using clutter-gtk 0.90, thus replacing BuildRequires
  pkgconfigu(clutter-gtk-0.19) with pkgconfig(clutter-gtk-0.90).
  Add moblin-panel-devices-clutter-gtk-0.90.patch to have configure
  detect the right thing.
* Thu Jun 10 2010 awafaa@opensuse.org
- Initial import into openSUSE version 0.1.21
