Name: mozart2
Summary: Mozart Programming System v2
Version: 2.0.1
Release: 1
Group: Development/Languages
License: BSD 2
URL: https://github.com/mozart/mozart2
Source0: http://downloads.sourceforge.net/project/%{name}/%{name}-%{version}.tar.gz
BuildRequires: desktop-file-utils
BuildRequires: tcl8.6-devel
BuildRequires: tk8.6-devel
Requires: emacs
Requires: tk

%description
The Mozart Programming System is an open source implementation of Oz 3.

%prep
%setup -q

%build
%cmake
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}

%files
%{_bindir}/oz*
%{_datadir}/applications/*.desktop
%{_datadir}/icons
%{_datadir}/mozart

%changelog
* Tue Feb 02 2021 Wei-Lun Chao <bluebat@member.fsf.org> - 2.0.1
- Rebuilt for Fedora
* Sun Jul 04 2010 Eric Noulard <eric.noulard@gmail.com> - 2.0.1-1
- Generated by CPack RPM (no Changelog file were provided)
