Name: kdiskmark
Summary: A simple open source disk benchmark tool for Linux distros
Version: 1.6.2
Release: 1
Group: Applications/System
License: GPLv3
URL: https://github.com/JonMagon/KDiskMark
Source0: KDiskMark-%{version}.tar.gz
BuildRequires: desktop-file-utils
BuildRequires: qt5-devel
BuildRequires: cmake
Requires: fio

%description
KDiskMark is an HDD and SSD benchmark tool with a very friendly graphical user
interface. KDiskMark with its presets and powerful GUI calls Flexible I/O Tester
and handles the output to provide an easy to view and interpret comprehensive
benchmark result.

%prep
%setup -q -n KDiskMark-%{version}

%build
%cmake
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}

%files
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/%{name}

%changelog
* Mon Oct 05 2020 Wei-Lun Chao <bluebat@member.fsf.org> - 1.6.2
- Rebuild for Fedora
* 2010  7月 04 日 Eric Noulard <eric.noulard@gmail.com> - 1.6.2-1
- Generated by CPack RPM (no Changelog file were provided)
