Name:           perl-Gtk3-SimpleList
Version:        0.17
Release:        1
Summary:        Simple interface to Gtk3's complex MVC list widget
# lib/Gtk3/SimpleList.pm:   LGPLv2+
# README:                   LGPLv2+ or Artistic 2.0
License:        LGPLv2+ and (LGPLv2+ or Artistic 2.0)
URL:            http://search.cpan.org/dist/Gtk3-SimpleList/
Source0:        http://www.cpan.org/authors/id/T/TV/TVIGNAUD/Gtk3-SimpleList-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
# Run-time:
BuildRequires:  perl(Carp)
BuildRequires:  perl(Gtk3)
# Gtk3::TreeView not provided by Gtk3 because the Perl module names are generated
# gtk3 gobject typelib at run-time.
# Tests:
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))

%description
Gtk3 has a powerful, but complex MVC (Model, View, Controller) system used
to implement list and tree widgets. Gtk3::SimpleList Perl module automates the
complex setup work and allows you to treat the list model as a more natural
list of lists structure.

%prep
%setup -q -n Gtk3-SimpleList-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
make %{?_smp_mflags}

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%license COPYING
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Mar 09 2018 Petr Pisar <ppisar@redhat.com> 0.17-1
- Specfile autogenerated by cpanspec 1.78.
