%global __os_install_post %{nil}

Summary:    Portable Forth Environment
Name:	    pfe
Version:    0.33.71
Release:    1
License:    LGPL
Group:	    Development/Languages
URL:	    http://sourceforge.net/projects/pfe
Source0:    http://prdownloads.sf.net/%{name}/%{name}-%{version}.tar.bz2
BuildRequires: gcc automake
BuildRequires: ncurses-devel

%package docs
Summary:	PFE Documentation
Group:		Development/Libraries
BuildRequires:  python2
BuildRequires:  xmlto

%package devel
Summary:	PFE Development Headers
Group:		Development/Libraries
Requires:       pfe

%description
The Portable Forth Environment is a Forth Engine completly written in C.
It has a module concept so it can be extended with C modules. It is
completly multithreaded, and implements the DPANS94, the proposed ANSI
standard on Forth.

Available rpmbuild rebuild options:
--with : regs fast call sbr modules testmodule

%description docs
The Portable Forth Environment.
The documentation, mostly autogenerated. (as for http://PFE.sf.net)

%description devel
The Portable Forth Environment.
The header file for compiling extension modules for
use by the forth engine, or for compiling applications
that use the forth library as a scripting engine.

The headers are namespace clean, i.e. all symbols
have a prefix to distinguish them from other symbols.

%prep
%setup -q
sed -i 's|python|python2|' doc/Makefile*
#sed -i 's|fprintf(f, \*p);|fprintf(f, "%s", *p);|' pfe/option-set.c
# % configure - the configure macro has weird interactions with pfe builds
export pfemoduleslibdir=%{_libdir}
CFLAGS="$RPM_OPT_FLAGS -Wno-format-security" sh configure \
       --prefix=%{_prefix} \
        --bindir=%{_bindir} \
        --sbindir=%{_sbindir} \
        --sysconfdir=%{_sysconfdir} \
        --datadir=%{_datadir} \
        --includedir=%{_includedir} \
        --libdir=%{_libdir} \
        --libexecdir=%{_libexecdir} \
        --localstatedir=%{_localstatedir} \
        --sharedstatedir=%{_sharedstatedir} \
        --mandir=%{_mandir} \
        --infodir=%{_infodir} \
    %{?_with_call: %{!?_with_sbr: --with-call-threading}} \
    %{?_with_call: %{?_with_sbr: --with-sbr-call-threading}} \
    %{!?_with_call: %{?_with_sbr: --with-sbr-threading}} \
    %{?_with_fast: --with-static-regs} \
    %{?_without_modules: --without-modules} \
    %{?_without_testmodule: --without-testmodule} \
    --without-regs

%build
export SHOWBADTESTOUT=y
make
make check
make mans
#make docs

%install
rm -rf %{buildroot}
mkdir  %{buildroot}
make install DESTDIR=%{buildroot}
make install-mans DESTDIR=%{buildroot}
#make install-docs DESTDIR=%{buildroot}
rm %{buildroot}%{_bindir}/pfe-exec
rm %{buildroot}%{_bindir}/pfe
#rmdir %{buildroot}%{_infodir}

echo ==========================
cat %buildroot%_libdir/pkgconfig/*.pc
echo ==========================

%clean
rm -rf %{buildroot}

%files
%doc ChangeLog
     %{_bindir}/%{name}*
     %{_libdir}/lib%{name}*.so.*
%dir %{_libdir}/%{name}-*
     %{_libdir}/%{name}-*/*.so
%dir %{_datadir}/%{name}
     %{_datadir}/%{name}/*
     %{_mandir}/man1/*

#files docs
#dir %{_infodir}/../doc/%{name}
#    %{_infodir}/../doc/%{name}/*

#post docs
#echo "PFE Documentation installed"
#: scrollkeeper-install && /bin/true

%files devel
     %{_bindir}/*-exec-*
     %{_mandir}/man3/*
%dir %{_prefix}/include/%{name}
     %{_prefix}/include/%{name}/*
     %{_libdir}/lib%{name}*.so
     %{_libdir}/lib%{name}*.la
     %{_libdir}/lib%{name}*.a
     %{_libdir}/%{name}-*/*.la
     %{_libdir}/%{name}-*/*.a
     %{_libdir}/%{name}-*/renamed/*
     %{_libdir}/pkgconfig/*.pc

%changelog
* Sun Dec 12 2021 Wei-Lun Chao <bluebat@member.fsf.org> - 0.33.71
- Rebuilt for Fedora
