%undefine _debugsource_packages
%define themepack qingy_0.3_themepack_1.0

Summary: Qingy Is Not GettY
Name: qingy
Version: 1.0.0
Release: 33.1
License: GPL
Group: Applications/System
Source0: https://easynews.dl.sourceforge.net/sourceforge/qingy/%{name}-%{version}.tar.bz2
Source1: https://easynews.dl.sourceforge.net/sourceforge/qingy/%{themepack}.tar.bz2
URL: https://qingy.sourceforge.net/about.php
BuildRequires: xorg-x11-proto-devel, ncurses-devel, libXScrnSaver-devel
BuildRequires: compat-openssl10-devel
BuildRequires: directfb-devel
Requires: directfb

%description
qingy is a replacement for getty. Written in C, it uses DirectFB to
provide a fast, nice GUI without the overhead of the X Window
System. It allows the user to log in and start the session of his
choice (text console, gnome, kde, wmaker, ...).

%package themes
Summary: Themes for qingy
Group: Applications/System
Requires: %{name} >= 0.3
BuildArch: noarch

%description themes
The official themepack for qingy.

%prep
%setup -q -a 1
sed -i 's|CPUFLAGS=".*"|CPUFLAGS="-fPIC"|' configure

%build
%configure %{?acflags}
sed -i 's|gcc$|gcc -Wl,--allow-multiple-definition -fPIC|' src/libraries/Makefile src/DirectFB/Makefile
sed -i 's|-Wall|-Wall -fPIC|' Makefile */Makefile
%__make %{?mflags}

%install
%__rm -rf $RPM_BUILD_ROOT
%__make install DESTDIR=$RPM_BUILD_ROOT %{?mflags_install}
%__install -D -m 644 media/sessions/emacs $RPM_BUILD_ROOT%{_sysconfdir}/%{name}/sessions/emacs
%__sed -i 's/etc\/X11\/Sessions/usr\/share\/xsession/' $RPM_BUILD_ROOT%{_sysconfdir}/%{name}/settings
%__rm -rf $RPM_BUILD_ROOT%{_datadir}/info/dir

# Install themes
%{__mkdir_p} $RPM_BUILD_ROOT%{_sysconfdir}/%{name}/themes
%{__cp} -a %{themepack}/[a-z]* $RPM_BUILD_ROOT%{_datadir}/%{name}/themes/

%clean
%__rm -rf $RPM_BUILD_ROOT

%files
%doc README INSTALL COPYING TODO AUTHORS NEWS ChangeLog doc
%dir %{_sysconfdir}/%{name}
%{_sysconfdir}/%{name}/*.sh
%config(noreplace) %{_sysconfdir}/pam.d/%{name}
%config(noreplace) %{_sysconfdir}/%{name}/settings
%config(noreplace) %{_sysconfdir}/%{name}/welcomes
%config(noreplace) %{_sysconfdir}/%{name}/sessions/emacs
%{_sbindir}/%{name}*
%{_libdir}/%{name}
%{_datadir}/%{name}/themes/d*
%{_datadir}/info/%{name}.info*

%files themes
%doc %{themepack}/README
%{_datadir}/%{name}/themes/[^d]*

%changelog
* Sat Apr 23 2011 Wei-Lun Chao <bluebat@member.fsf.org> - 1.0.0
- Rebuilt for Fedora
* Thu Feb 03 2005 Mezzanine <mezzanine@kainx.org>
- Specfile auto-generated by Mezzanine
