Name: yagy
Summary: Yet Another GUI for Yacas
Version: 1.1.0
Release: 7.1
Group: Applications/Engineering
License: LGPLv2.1+
URL: https://github.com/grzegorzmazur/yagy
Source0: %{name}-%{version}.tar.gz
BuildRequires: cmake
BuildRequires: qt5-qtbase-devel
BuildRequires: qt5-qtwebkit-devel
BuildRequires: utf8cpp-devel
BuildRequires: python-docutils
BuildRequires: yacas-devel

%description
Yagy is a graphical user interface for Yacas, a small and highly flexible
computer algebra system.

%prep
%setup -q
%ifarch x86_64 aarch64
sed -i 's|lib/libyacas\.a|lib64/libyacas.a|' CMakeLists.txt YAGY.pro
%endif

%build
%cmake
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}

%files
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/doc/%{name}
%{_mandir}/man1/%{name}.1.*
%{_datadir}/%{name}

%changelog
* Thu Aug 11 2016 Wei-Lun Chao <bluebat@member.fsf.org> - 1.1.0
- Rebuild for Fedora
* Sun Jul 04 2010 Eric Noulard <eric.noulard@gmail.com> - 1.1.0-1
Generated by CPack RPM (no Changelog file were provided)

