%global debug_package %{nil}

Summary: Athena-based Minesweeper Clone
Name: xbomb
Version: 2.2b
Release: 5.1
License: GPL
Group: Amusements/Games
URL: http://www.gedanken.org.uk/software/xbomb/
Source: http://www.gedanken.org.uk/software/xbomb/download/%{name}-%{version}.tgz
BuildRequires: libX11-devel, libXaw-devel

%description
xbomb is a clone of the Windows Minesweeper program using the standard
X11 Athena widget set with squares, hexagons or triangles.

%prep
%setup -q 

%build
make

%install
%{__mkdir_p} $RPM_BUILD_ROOT%{_bindir} $RPM_BUILD_ROOT%{_mandir}/man6 $RPM_BUILD_ROOT%{_datadir}/X11/app-defaults
%{__install} -m 0755 %{name} $RPM_BUILD_ROOT%{_bindir}
%{__install} -m 0644 %{name}.6 $RPM_BUILD_ROOT%{_mandir}/man6
%{__install} -m 0644 %{name}.ad $RPM_BUILD_ROOT%{_datadir}/X11/app-defaults/XBomb

%clean
rm -rf $RPM_BUILD_ROOT

%files
%doc README COPYING ChangeLog
%{_datadir}/X11/app-defaults/XBomb
%{_bindir}/%{name}
%{_mandir}/man*/*

%changelog
* Mon Mar 02 2015 Wei-Lun Chao <bluebat@member.fsf.org> - 2.2b
- Rebuild for Fedora
* Sun Jan 08 2006 Mezzanine <mezzanine@kainx.org>
- Specfile auto-generated by Mezzanine
