%undefine _debugsource_packages

Summary: Uses hopalong algorithm to decorate root window
Name: xmartin
Version: 2.2 
Release: 11.1
Source: ftp://gatekeeper.dec.com/pub/X11-contrib/xmartin.tar.Z
License: distributable
Group: X11/Amusements
BuildRequires: imake
BuildRequires: libX11-devel
BuildRequires: libXext-devel

%description
Decorate the root window with images generated by the hopalong algorithm.

%prep
%setup -q -c

%build
xmkmf
make

%install
install -Dm755 xmartin %{buildroot}%{_bindir}/%{name}
install -Dm755 xmartin+.pl %{buildroot}%{_bindir}/%{name}+
install -Dm644 xmartin._man %{buildroot}%{_mandir}/man1/%{name}.1

%files
%{_bindir}/xmartin
%{_bindir}/xmartin+
%{_mandir}/man1/xmartin.1.*

%changelog
* Tue Dec 10 2013 Wei-Lun Chao <bluebat@member.fsf.org> - 2.2
- Rebuilt for Fedora
* Sun Oct 20 1996 chorn@warwick.net
- Initial package
